"""Added Artist Cover

Revision ID: 0b923ca42da9
Revises: 008d891915f5
Create Date: 2024-10-04 23:39:32.600132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b923ca42da9'
down_revision: Union[str, None] = '008d891915f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('cover', sa.String(length=255), nullable=True))
    op.drop_column('songs', 'artist_slug')
    op.drop_column('songs', 'album_slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('album_slug', sa.VARCHAR(length=255), nullable=False))
    op.add_column('songs', sa.Column('artist_slug', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('artists', 'cover')
    # ### end Alembic commands ###
