"""Removed unique requirement for instrument colour

Revision ID: 7217e8382f57
Revises: 96511fa14049
Create Date: 2025-03-27 15:50:01.197450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7217e8382f57'
down_revision: Union[str, None] = '96511fa14049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_instruments_colour', table_name='instruments')
    op.create_index(op.f('ix_instruments_colour'), 'instruments', ['colour'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruments_colour'), table_name='instruments')
    op.create_index('ix_instruments_colour', 'instruments', ['colour'], unique=True)
    # ### end Alembic commands ###
