"""Added slug fields to Song model

Revision ID: aa35b403592a
Revises: 
Create Date: 2024-10-04 14:33:23.518445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa35b403592a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('song_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_song_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.Column('artist_id', sa.String(length=255), nullable=True),
    sa.Column('artist_slug', sa.String(length=255), nullable=False),
    sa.Column('album', sa.String(length=100), nullable=True),
    sa.Column('album_id', sa.String(length=255), nullable=True),
    sa.Column('album_slug', sa.String(length=255), nullable=False),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('track_length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('song_id'),
    sa.UniqueConstraint('album_slug'),
    sa.UniqueConstraint('artist_slug')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('spotify_user_id', sa.String(length=255), nullable=True),
    sa.Column('is_authenticated', sa.Boolean(), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('spotify_user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('collections',
    sa.Column('collection_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=50), nullable=True),
    sa.Column('collection_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.song_id'], ),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('expires_in', sa.DateTime(), nullable=True),
    sa.Column('token_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('segments',
    sa.Column('segment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('segment_name', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('segment_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('segment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segments')
    op.drop_table('tokens')
    op.drop_table('collections')
    op.drop_table('users')
    op.drop_table('songs')
    # ### end Alembic commands ###
