"""Add colour column to instruments table

Revision ID: 2612f39befb6
Revises: 6b515f4562d6
Create Date: 2025-03-24 21:38:56.893224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2612f39befb6'
down_revision: Union[str, None] = '6b515f4562d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('colour', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_instruments_colour'), 'instruments', ['colour'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruments_colour'), table_name='instruments')
    op.drop_column('instruments', 'colour')
    # ### end Alembic commands ###
