"""Add lead column to segements table

Revision ID: 96511fa14049
Revises: a4d7b0196990
Create Date: 2025-03-24 22:01:17.851025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96511fa14049'
down_revision: Union[str, None] = 'a4d7b0196990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('lead', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'lead')
    # ### end Alembic commands ###
